settings:
  mysql:
    host: 'localhost'
    user: 'root'
    password: 'root'
    database: 'nxseason'
  general:
    collect: false # se tiver false o comando /temporada resgatar não vai funcionar e o /temporada coletar irá funcionar e assim vice-versa.
    items_blacklist:
      - MOB_SPAWNER
      - DIAMOND